CREATE TABLE otp_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL,
    token_hash   VARCHAR(100) NOT NULL,
    expires_at   TIMESTAMP    NOT NULL,
    used         BOOLEAN      NOT NULL DEFAULT FALSE,
    attempts     INTEGER      NOT NULL DEFAULT 0,
    created_at   TIMESTAMP    NOT NULL,
    CONSTRAINT fk_otp_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_otp_tokens_user_unused ON otp_tokens (user_id, used, expires_at);
