CREATE TABLE availability (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supervisor_id     BIGINT        NOT NULL,
    date              DATE          NOT NULL,
    start_time        TIME          NOT NULL,
    end_time          TIME          NOT NULL,
    duration_minutes  INTEGER       NOT NULL,
    meet_url          VARCHAR(500)  NOT NULL,
    created_at        TIMESTAMP     NOT NULL,
    CONSTRAINT fk_availability_supervisor FOREIGN KEY (supervisor_id) REFERENCES users (id)
);

CREATE INDEX idx_availability_supervisor_date ON availability (supervisor_id, date);
