-- No FK constraints to users — users live in user-service's DB.
-- Referential integrity is best-effort; booking-service trusts the user-service
-- Feign call to resolve student_id / supervisor_id.
CREATE TABLE bookings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id      BIGINT        NOT NULL,
    supervisor_id   BIGINT        NOT NULL,
    name            VARCHAR(255)  NOT NULL,
    group_number    INTEGER       NOT NULL,
    project         VARCHAR(200)  NOT NULL,
    slot_at         TIMESTAMP     NOT NULL,
    status          VARCHAR(16)   NOT NULL,
    meet_url        VARCHAR(500)  NOT NULL,
    reminder_sent   BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP     NOT NULL
);

CREATE INDEX idx_bookings_reminder ON bookings (status, reminder_sent, slot_at);
CREATE INDEX idx_bookings_student  ON bookings (student_id);
CREATE INDEX idx_bookings_supervisor ON bookings (supervisor_id);
